### ISSUE TITLE
build failed on Win 10

### ISSUE THREAD

**Issue by schlefix** [TNkemdilim/wifi-rs#3]
Hi there!
I was looking for a multi-platform wifi crate and stumbled upon your work... sadly I am unable to build it due to the following Error:

> Compiling wifi-rs v0.2.0
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> X\Y\Z\.cargo\registry\src\github.com-1ecc6299db9ec823\wifi-rs-0.2.0\src\connectivity\providers\windows.rs:48:18
    |
48  |                 &format!("name={}", *self.connection.unwrap().ssid),
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

sorry for the Inconvenience and thanks for your help! ;)

**Comment by TNkemdilim** [comment]
Hello @schlefix.

Thanks for pointing out the error.

I'll look into it, although it might take roughly a day for me to get my hands on a windows machine since my primary OS is Linux.

I would be glad if you could also try submitting a PR to fix the issue.

**Comment by schlefix** [comment]
all right... i prepare a PR ;) got a not that nice but working solution ;)

**Comment by schlefix** [comment]
... i am currently unable to login into github from my workplace  o.O 

more time to test and make a better PR ;)

**Comment by TNkemdilim** [comment]
Sure! Please do take your time :smiley:.

**Comment by TNkemdilim** [comment]
Hello @schlefix.

Just wanted to ask if you've been less busy till give the windows build some time.

I'll very much appreciate it.

Thanks.

**Comment by schlefix** [comment]
I am sorry... I forgot it completely over the holydays. Unfortunately I am currently in the same situation (no Windows at Home... only at work)... plus: this is not my number one priority  ;) 

As i am able to recal my workaround was simply to copy the ssid string/slice into a local variable... Not quite a clean solution ;)

I may be able to look into it at the end of next week... sorry

**Comment by schlefix** [comment]
unfortunately i am not able to create an PR... or I am too stupid (normaly i create a branch, push to new branch and create a merge-request)

replaced &format!("name={}", *self.connection.unwrap().ssid) with &format!("name={}", ssid) and this builds at least...

using the ssid from the parameter is (in my view) already ensured by Self::add_profile(ssid,password)?
if add_profile returns Ok(..) then ssid is valid and can be used ?!
